react: re-generate by imd with true imports for enums types instead of explicit acceptable values (53), known conflict (error TS2300: Duplicate identifier 'LocalizationTypes')