Release 18.1.3 Cherry-picked changesets:   487f2e8 Ilya Kharchenko - Fix format declaration (#3912)   e907484 Ilya Kharchenko - Update TS declarations (#3909)   87b07c6 Yana Yarovaya - Fix Scheduler working when groupOrientation is set without groups  (T632819) (#3914)   eb15455 groshenkovamarina - Implement styles for material theme in dxLookup (#3897)   0073cfe Yana Yarovaya - Fix Scheduler IE tests without jquery (#3917)   2602b5a Alexander Komarov - Fix rendering of editor in "anyof" operation (#3919) a12dd36 Konstantin Volnyagin - DataGrid: Fix virtual scrolling bugs with large data (#3922)   416b8d9 Alexander Komarov - DataGrid - Fix restoring of old filter values when the filterSyncEnabled option is set to true (#3918)   9bf0cfa Yana Yarovaya - Fix Scheduler appointments resizing when groupOrientation is vertical (T627091) (#3923) d760a60 Yana Yarovaya - Fix optionChanging for Scheduler Resources demo in AngularJS (#3925)   cf4dc51 Yana Yarovaya - Fix Firefox & IE Scheduler tests (#3926)   f43f5fd Alexander Komarov - DataGrid: optionChanged should not be fired for the command column (T630149) (#3927)   6b30e61 Alexey Babich - Fix template for accordion title in material theme (T633478) (#3930)   62afef6 Alexander Komarov - TreeList - Fix error "TypeError: this.callBase is not a function" when display a context menu (#3934)   e2735ce Konstantin Volnyagin - DataGrid: Fix asynchronous rendering problems during virtual scrolling (#3936)   f1ef43d Sergey Zvyagin - Deprecate 'android5' theme (#3938)   92ed53c Ksenia Mordalyuk - Fix multiple cell selection in vertical grouped week view in Scheduler (T628219) (#3937)   42adc85 Konstantin Volnyagin - DataGrid: Fix null reference exception after change rtlEnabled option if content is scrolled (#3939)   fdbca81 Pavel Gruba - Fix tree map click event (T633107) (#3944)   9ac9c65 Ksenia Mordalyuk - Fix IE tests in Scheduler after #3937 (#3950)   34d5ca2 Alexey Babich - Remove focus state of the button according to Material 2.0 (#3952)   544b9f8 Alexey Babich - Use local Roboto fonts only as fallbacks (#3961)   0c0ca58 anna-zhernovkova - Add metadata for localization methods (#4002)   a4832fd alexander-kotov-dx - Fix ThemeBulder less parser (#3991)