Move components input to separate class (#11872)
* Move components input to separate class

* fix 'Cannot find name 'h'.ts(2304)' in declarations

* fix error TS2345

* update generator

* remove component_declaration module

* Merge branch 'preact-button' of https://github.com/DevExpress/DevExtreme into new-design

# Conflicts:
#	js/renovation/button.tsx
#	js/renovation/widget.tsx