Freeze @types/node package due TS compilation errors
We get the following error:

TypeScript error: c:/Projects/DevExtreme/19.1/Build/Temp/DevExtreme.v19.1/repo/GitHub/node_modules/@types/node/globals.d.ts(318,65): error TS2339: Property 'toPrimitive' does not exist on type 'SymbolConstructor'.

after this change in @types/node@10.17.15

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42111/files#diff-ad3552bc3f967859ad249ffc9b9cf5c1R358