Revert "regenerate: react data_grid / tree_list lose defaultFilterPanel / onFilterPanelChange (aka subscribable), coz no more `@fires GridBaseOptions.onOptionChanged`), fails on pack all platforms - `error TS2707: Generic type 'FilterPanel<TComponent, TRowData, TKey>' requires between 1 and 3 type arguments` (no generic type param after generation)"
This reverts commit 83f67f7570305e7c84f41ffcc99667783dd4d11f.