DataGrid - The TypeError: this._contentReadyAction is not a function is thrown after widget disposed if renderAsync property is set to true (T1138639)